jobs:
  - script: >
      multibranchPipelineJob("GTT/DevOps-Build/astro-devops-training") 
      {
        branchSources {
          git {
            id = "astro-devops-training"
            remote("git@bitbucket.org:astrosolutions-co-th/astro-devops-training.git")
            credentialsId("pjames_bitbucket_ssh_private_key")
            includes("develop main")
          }
        }

        orphanedItemStrategy {
            discardOldItems {
                numToKeep(20)
            }
        }
      }