jobs:
  - script: >
      folder('GTT')
  - script: >
      folder('GTT/DevOps-Build')
  - script: >
      multibranchPipelineJob("GTT/DevOps-Build/astro-devops-training")
      {
        branchSources {
          git {
            id = "astro-devops-training"
            remote("git@bitbucket.org:astrosolutions-co-th/astro-devops-training.git")
            credentialsId("pjames-bitbucket-ssh-private-key")
            includes("develop main")
          }
        }

        factory
        {
            remoteJenkinsFileWorkflowBranchProjectFactory 
            {
                remoteJenkinsFile("Jenkinsfile_Common")
                localMarker("")
                matchBranches(false)
                fallbackBranch("master")
            }
        }

        properties {
            library('Common-Share-Libs@main')
        }

        configure { project ->
            def factoryNode = project / 'factory'
            factoryNode << owner(class:'org.jenkinsci.plugins.workflow.multibranch.WorkflowMultiBranchProject', reference:'../..')
        
            factoryNode << remoteJenkinsFileSCM(class:'hudson.plugins.git.GitSCM') {
                userRemoteConfigs 
                {
                    'hudson.plugins.git.UserRemoteConfig' 
                    {
                        url('git@bitbucket.org:astrosolutions-co-th/astro-gtt-jenkins-files.git')
                        credentialsId('pjames-bitbucket-ssh-private-key')
                    }
                }

                branches 
                {
                    'hudson.plugins.git.BranchSpec' 
                    {
                        name('main')
                    }
                }                    
            }
        }

        configure { job ->
            job / 'properties' << 'com.cloudbees.plugins.credentials.SystemCredentialsProvider' {
                'domainCredentials' {
                    'com.cloudbees.plugins.credentials.domains.Domain' {
                        'name'('Global')
                        'specifications' {
                            'com.cloudbees.plugins.credentials.domains.HostnameSpecification' {
                                'host'('bitbucket.org')
                            }
                        }
                    }
                }
            }

            job / 'libraries' << 'com.cloudbees.jenkins.plugins.bitbucket.BranchSource' {
                'id'('astro-jenkins-share-libs')
                'remote'('git@bitbucket.org:astrosolutions-co-th/astro-jenkins-share-libs.git')
                'credentialsId'('pjames-bitbucket-ssh-private-key')
                'includes'('main')
            }
        }

        orphanedItemStrategy {
            discardOldItems {
                numToKeep(20)
            }
        }
      }
